/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.peacetrue.modelgenerator;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.Test;

import static org.junit.Assert.assertNotNull;

/**
 * A simple unit test for the 'com.github.peacetrhue.modelgenerator.greeting' plugin.
 */
public class ModelGeneratorPluginTest {

    @Test
    public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply(ModelGeneratorPlugin.class);

        // Verify the result
        ModelGeneratorTask generateModel = (ModelGeneratorTask) project.getTasks().findByName("generateModel");
        assertNotNull(generateModel);
        String path = "/Users/xiayx/Documents/Projects/peacetrue-modelgenerator-gradle-plugin";
        generateModel.setProjectPath(path + "/sample");
        generateModel.setPropertiesPath("file:" + path + "/src/test/resources/application-datasource.properties");
        generateModel.generate();
    }

}
