/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.peacetrue.modelgenerator;

import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.junit.Test;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.nio.file.Files;

/**
 * A simple functional test for the 'com.github.peacetrhue.modelgenerator.greeting' plugin.
 */
public class ModelGeneratorPluginFunctionalTest {

    @Test
    public void canRunTask() throws IOException {
        // Setup the test build
        File projectDir = new File("build/functionalTest");
        Files.createDirectories(projectDir.toPath());
        writeString(new File(projectDir, "settings.gradle"), "");
        writeString(new File(projectDir, "build.gradle"),
                "buildscript {\n" +
                        "    repositories {\n" +
                        "        maven { url \"https://oss.sonatype.org/content/repositories/snapshots/\" }\n" +
                        "    }\n" +
                        "\n" +
                        "    dependencies {\n" +
                        "        classpath('com.github.peacetrue.modelgenerator:peacetrue-modelgenerator-template-aum:1.0-SNAPSHOT') {\n" +
                        "            exclude group: 'ch.qos.logback'\n" +
                        "        }\n" +
                        "    }\n" +
                        "}\n" +
                        "plugins {\n" +
                        "    id('com.github.peacetrue.modelgenerator')\n" +
                        "}\n" +
                        "generateModel {\n" +
//                        "    propertiesPath = 'file:/Users/xiayx/Documents/Projects/peacetrue-modelgenerator-gradle-plugin/src/test/resources/application-datasource.properties'\n" +
//                        "    projectPath = '/Users/xiayx/Documents/Projects/peacetrue-modelgenerator-gradle-plugin/sample'\n" +
                        "}");

        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withArguments("generateModel");
        runner.withProjectDir(projectDir);
        BuildResult result = runner.build();

        // Verify the result
//        assertTrue(result.getOutput().contains("Hello from plugin 'com.github.peacetrhue.modelgenerator.greeting'"));
    }

    private void writeString(File file, String string) throws IOException {
        try (Writer writer = new FileWriter(file)) {
            writer.write(string);
        }
    }
}
