/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.peacetrue.modelgenerator;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

public class ModelGeneratorPlugin implements Plugin<Project> {

    public void apply(Project project) {
        project.getTasks().register("generateModel", ModelGeneratorTask.class, task -> {
            //默认为当前模块resources下的application-datasource.properties
            task.setPropertiesPath(String.format("file:%s/src/main/java/resources/application-datasource.properties", project.getProjectDir().getPath()));
            //默认为项目的根目录
            task.setProjectPath(project.getRootDir().getAbsolutePath());
        });
    }

}
